# Lifted from 
# https://github.community/t/can-github-actions-directly-edit-files-in-a-repository/17884/2
# and https://github.community/t/possible-to-commit-files-after-workflow-runs/17824/2

name: expand-events
on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: x64
    - name: Install Python packages
      uses: BSFishy/pip-action@v1
      with:
        packages: |
         frontmatter
         recurrent
    - name: Run my Python script
      run: python ./.github/workflows/expand-events.py
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto expand events"
    - name: fetch from main
      run: git fetch origin main
    - name: push code to main
      run: git push origin HEAD:main
